---
- name: deploy latest app code
  hosts: webservers
  remote_user: zoomhub
  vars_files:
    - [ 'vars.yml', 'vars.default.yml' ]
    - secrets.vault.yml
  tasks:
  - name: update service upstart script
    sudo: true
    template: src=roles/web/templates/service.conf.j2
              dest=/etc/init/{{ service }}.conf

  - name: update app source
    git: repo={{ app_repo }} dest={{ app_root }} version={{ app_version }}
         force=no

  - name: npm update
    npm: path={{ app_root }} state=latest

  - name: remove Streamline.js cache
    file: path={{ admin_home}}/.streamline state=absent

  - name: start redis
    sudo: yes
    service: name=redis_6379 state=started

  - name: run app
    sudo: yes
    service: name={{ service }} state=restarted
