---
- name: Update APT package cache
  apt:
    update_cache: yes

- name: Upgrade APT to the latest packages
  apt:
    upgrade: safe

- name: Install unattended-upgrades
  apt:
    pkg: unattended-upgrades

- name: Adjust APT update intervals
  template: src=apt/10periodic dest=/etc/apt/apt.conf.d/10periodic

- name: Ensure unattended-upgrades only installs from security
  lineinfile:
    dest=/etc/apt/apt.conf.d/50unattended-upgrades
    regexp="distro_codename\}\-updates"
    state=absent
